services:
  db:
    image: postgres:latest
    container_name: blog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: blog_backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: blog_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    container_name: blog_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    links:
      - backend
      - frontend

volumes:
  db_data: